---
  - name: Check if Apache exists
    shell: systemctl status apache2
    failed_when: false
    changed_when: false
    register: apache_status

  - name: Install Apache
    apt:
      name: apache2
      state: present
    when: apache_status.rc|int != 0

  - name: Install php
    apt:
      name: php
      state: present

  - name: Enable and start apache
    systemd:
      state: started
      enabled: yes
      name: apache2
    when: apache_status.rc|int != 0

  - name: Restart and reload apache
    systemd:
      state: restarted
      daemon-reload: yes
      name: apache2
    when: apache_status.rc|int == 0
