--- 
  - name: Ensure Chocolatey itself is installed
    win_chocolatey:
      name: chocolatey
 
  - name: Confirm Prompts Automatically
    win_chocolatey_feature:
      name: allowGlobalConfirmation
      state: enabled

  - name: Essentials
    ignore_errors: yes
    win_chocolatey:
      name: '{{ item }}'
      state: present
      ignore_checksums: yes
    loop:
    - brave
    - microsoft-windows-terminal
    - hwinfo
    - msiafterburner
    - steam
    - vscode
    - geforce-experience
    - 7zip
    - firefox

  - name: Work Applications
    ignore_errors: yes
    win_chocolatey:
      name: '{{ item }}'
      state: present
      ignore_checksums: yes
    loop:
    - microsoft-teams.install
    - zoom
    - teamviewer

  - name: System Settings
    ignore_errors: yes
    win_chocolatey:
      name: '{{ item }}'
      state: present
      ignore_checksums: yes
    loop:
    - classic-shell
    - f.lux
    - wsl
    - logitechgaming
    - treesizefree
   
  - name: Additional Applications
    ignore_errors: yes
    win_chocolatey:
      name: '{{ item }}'
      state: present
      ignore_checksums: yes
    loop:
    - vlc
    - eartrumpet
    - sharex
    - zerotier-one
    - spotify
    - discord
    - filezilla
    - equalizerapo
    - calibre
    - sumatrapdf.install
    - qbittorrent
    - kindle
    - wireshark
    - minecraft-launcher
    - epicgameslauncher
    

# cannot install
# mullvad
# onedrive
# cisco VPN

# Manual/Might not work (still with PoSH)
# spotify
# microsoft-windows-terminal

# Game Mods
# MGSV5 - FoV fix, Infinite Heaven (Snakebite Mod Manager)
# BakkesMod
# Minecraft - BSL Shader, Java, and Optifine

# Backup
# Desktop/Home Folder
