---
 # - name: Check if Apache exists # btw this sucks, systemctl status to check if apache is installed?
 #   shell: systemctl status apache2
 #   #failed_when: false
 #   changed_when: false
 #   register: apache_systemd_status

 # - name: Set apache status if not found
 #   set_fact:
 #     apache_status: 2
 #   when: ( apache_systemd_status is defined ) and ( apache_systemd_status is mapping ) # if systemd doesn't find apache, returns a dict..

 # - name: Set apache status if found
 #   set_fact:
 #     apache_status: 0
 #   when: apache_systemd_status is not mapping # this is stupid, but if not a dict it probably exists
  - name: "Check if APACHE is installed"
    package_facts:
      manager: "auto"
  - name: "Apache result"
    debug:
      msg: "Apache found"
    when: "'apache2' in ansible_facts.packages"
  - name: "Apache result"
    debug:
      msg: "Apache NOT found"
    when: "'apache2' not in ansible_facts.packages"

  - name: install apt fail2ban packages
    apt:
      name: fail2ban
      state: present

  - name: override the basic fail2ban configuration with .local file
    copy:
      src: ../files/fail2ban-jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
    when: "'apache2' not in ansible_facts.packages"
    notify:
      - restart fail2ban

  - name: Apache only jail.local
    copy:
      src: ../files/fail2ban-apache_jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
    when: "'apache2' in ansible_facts.packages"
    register: apache_only_jail
    notify:
      - restart fail2ban

  - name: Apache 404 filter
    copy:
      src: ../files/fail2ban-apache-404.conf
      dest: /etc/fail2ban/filter.d/apache-404.conf
      owner: root
      group: root
      mode: 0644
    when: "'apache2' in ansible_facts.packages"
    register: apache_404_jail
    notify:
      - restart fail2ban

  - name: make sure fail2ban is enabled on boot and restarted
    systemd:
      name: fail2ban
      enabled: yes
      state: started
