---
# DISABLED:
# when != didn't work for whatever reason
# and fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_eth0' is undefined"}
# set /etc/hosts
- name: Configure hosts file
  become: yes
  template:
    src: ../templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname != "asimov.boll"
# skip cause its a dns server
