---
      - name: Check if Apache exists
        shell: systemctl status apache2
        failed_when: false
        changed_when: false
        register: apache_status
        #when: apache_status.rc|int == 0

      - name: Check if Fail2ban exists
        shell: systemctl status fail2ban
        failed_when: false
        changed_when: false
        register: fail2ban_status
        #when: apache_status.rc|int == 0

      - name: Check if MySQL exists
        shell: systemctl status mysql
        failed_when: false
        changed_when: false
        register: mysql_status
        #when: apache_status.rc|int == 0  
        # needed for all agents, snmp user runs snmpd (ubuntu 18+, user is Debian-snmp)
      - name: Add Librenms Agent Dir
        file:
          path: /var/cache/librenms/
          owner: snmp
          group: snmp
          state: directory
          mode: '0755'
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

      - name: Add Librenms Agent Dir for newever ubuntu/debian versions
        file:
          path: /var/cache/librenms/
          owner: Debian-snmp
          group: Debian-snmp
          state: directory
          mode: '0755'
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '18.04'
    
      # adds apache agent if installed
      - name: Add Apache Agent
        get_url:
          url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/apache-stats.py
          dest: /etc/snmp/apache-stats.py
          owner: root
          group: root
          mode: '0755'
        when: apache_status.rc|int == 0

      - name: Install Apache Agent Apt Packages
        apt:
          pkg:
          - python-urlgrabber
          - python-pycurl
        when:  apache_status.rc|int == 0 and ansible_distribution_version == '16.04'

      # python-urlgrabber not in ubuntu 20?
      - name: Install Apache Agent Apt Packages
        apt:
          pkg:
          - python-pycurl
        when:  apache_status.rc|int == 0 and ansible_distribution_version >= '18.04'

      - name: Add extension to snmpd.conf for Apache
        lineinfile:
          path: /etc/snmp/snmpd.conf
          line: extend apache /etc/snmp/apache-stats.py
        when:  apache_status.rc|int == 0

      # doing same for mysql
      - name: Add MySQL SNMP Extend
        get_url:
          url: https://github.com/librenms/librenms-agent/raw/master/snmp/mysql
          dest: /etc/snmp/mysql
          owner: root
          group: root
          mode: '0755'
        when: mysql_status.rc|int == 0

      - name: Add extension to snmpd.conf for Mysql
        lineinfile:
          path: /etc/snmp/snmpd.conf
          line: extend mysql /etc/snmp/mysql
        when: mysql_status.rc|int == 0

       # make mysql.cnf in /etc/snmp/ - requires mysql user/pass
      - name: MySQL SNMP Extend conf file
        blockinfile:
          path: /etc/snmp/mysql.cnf
          create: yes
          group: snmp
          owner: snmp
          block: |
            <?php
            $mysql_user = 'cci-mysql';
            $mysql_pass = 'x2nXKkjtbuBjnu';
            $mysql_host = 'localhost';
            $mysql_port = 3306;
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04' and mysql_status.rc|int == 0
      
      - name: MySQL SNMP Extend conf file
        blockinfile:
          path: /etc/snmp/mysql.cnf
          create: yes
          group: Debian-snmp
          owner: Debian-snmp
          block: |
            <?php
            $mysql_user = 'cci-mysql';
            $mysql_pass = 'x2nXKkjtbuBjnu';
            $mysql_host = 'localhost';                                                                       
            $mysql_port = '3306';
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '18.04' and mysql_status.rc|int == 0

      - name: Install MySQL Agent Apt Packages
        apt:
          pkg:
          - php-cli
          - php-mysql
        when: mysql_status.rc|int == 0
      
      - name: Add Fail2ban SNMP Extend
        get_url:
          url: https://github.com/librenms/librenms-agent/raw/master/snmp/fail2ban
          dest: /etc/snmp/fail2ban
          owner: root
          group: root
          mode: '0755'
        when: fail2ban_status.rc|int == 0

      - name: Add extension to snmpd.conf for F2B
        lineinfile:
          path: /etc/snmp/snmpd.conf
          line: extend fail2ban /etc/snmp/fail2ban
        when: fail2ban_status.rc|int == 0
   
      - name: install apt fail2ban packages
        apt:
          name: libjson-perl
          state: present
        when: fail2ban_status.rc|int == 0
   
      - name: Create f2b group
        group:
          name: fail2ban
          state: present
        when: fail2ban_status.rc|int == 0
   
      - name: add snmp to fail2ban group, append doesn't make it their primary group
        user:
          name: snmp
          groups: fail2ban
          append: yes
        when: fail2ban_status.rc|int == 0 and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
   
      - name: group ownership for newer ubuntu versions
        user:
          name: Debian-snmp
          groups: fail2ban
          append: yes
        when: fail2ban_status.rc|int == 0 and ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '18.04'
   
      - name: Add lines to F2B systemd service
        blockinfile:
          path: /lib/systemd/system/fail2ban.service
          insertafter: '^\[Service\]'
          block: |
            ExecStartPost=/bin/sh -c "while ! [ -S /run/fail2ban/fail2ban.sock ]; do sleep 1; done"
            ExecStartPost=/bin/chgrp fail2ban /run/fail2ban/fail2ban.sock
            ExecStartPost=/bin/chmod 770 /run/fail2ban/fail2ban.sock
        when: fail2ban_status.rc|int == 0
        register: f2b_systemd
        notify:
          - restart fail2ban
          - reload systemd
        
     #  end of fixing permissions  
      - name: Add OS Updates SNMP extend
        get_url:
          url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/osupdate
          dest: /etc/snmp/osupdate
          owner: root
          group: root
          mode: '0755'
     
      - name: Add OS Update SNMP extend to snmpd.conf
        lineinfile:
          path: /etc/snmp/snmpd.conf
          line: extend osupdate /etc/snmp/osupdate
  
      # apply changes
      - name: Restart snmpd
        systemd:
         state: restarted
         name: snmpd
