---
# tasks file for common
#- name: Setup SNMP for Libre
#  import_tasks: snmp.yaml
- name: Setup Fail2ban
  import_tasks: fail2ban.yaml
#- name: Setup Libre Agents
#  import_tasks: libreagent.yaml
#- name: Setup Rsyslog for Graylog
#  import_tasks: rsyslog.yaml
- name: Setup ZSH for wbollock
  import_tasks: zsh.yaml
#NOTE: need to exclude asimov.boll from thise
- name: Set /etc/hosts
  import_tasks: hosts.yaml
- name: Install molly-guard 
  import_tasks: molly-guard.yaml
