---
  - name: Check if Apache exists
    shell: systemctl status apache2
    failed_when: false
    changed_when: false
    register: apache_status
    #when: apache_status.rc|int == 0

  - name: Check if Fail2ban exists
    shell: systemctl status fail2ban
    failed_when: false
    changed_when: false
    register: fail2ban_status
    #when: apache_status.rc|int == 0

  - name: Check if MySQL exists
    shell: systemctl status mysql
    failed_when: false
    changed_when: false
    register: mysql_status
    #when: apache_status.rc|int == 0

  - name: Check if apt installed
    stat: path=/usr/bin/apt
    register: apt_exists

  - name: Check if ansible installed
    stat: path=/usr/local/bin/ansible
    register: ansible_exists

  - name: Check if web15c has a zshrc
    stat: path=/home/web15c/.zshrc
    register: web15c_zshrc_exists

  - name: Make sure rsyslog is up to date
    apt:
      name: rsyslog
      state: present 

    # base file, all hosts get this
  - name: Basic syslog logging and forwarding to graylog
    copy:
      src: ../files/rsyslog-00-graylog.conf
      dest: /etc/rsyslog.d/00-graylog.conf
      owner: root
      group: root
      mode: '0644'
    when: inventory_hostname != "wboll.dev"
  #install rsyslog

  - name: wboll.dev only - Basic syslog logging and forwarding to graylog
    copy:
      src: ../files/rsyslog-00-graylog-wboll-dev.conf
      dest: /etc/rsyslog.d/00-graylog.conf
      owner: root
      group: root
      mode: '0644'
    when: inventory_hostname == "wboll.dev"


# adds access and error.log to logging if apache installed
  - name: Add rsyslog conf for apache
    copy:
      src: ../files/rsyslog-01-graylog_apache.conf
      dest: /etc/rsyslog.d/01-graylog_apache.conf
      owner: root
      group: root
      mode: '0644'
    when: apache_status.rc|int == 0

  - name: Add rsyslog conf for fail2ban
    copy:
      src: ../files/rsyslog-02-graylog_fail2ban.conf
      dest: /etc/rsyslog.d/02-graylog_fail2ban.conf
      owner: root
      group: root
      mode: '0644'
    when: fail2ban_status.rc|int == 0

  - name: Add rsyslog conf for apt
    copy:
      src: ../files/rsyslog-03-graylog_apt.conf
      dest: /etc/rsyslog.d/03-graylog_apt.conf
      owner: root
      group: root
      mode: '0644'
    when: apt_exists.stat.exists == True

  - name: Add rsyslog conf for mysql
    copy:
      src: ../files/rsyslog-04-graylog_mysql.conf
      dest: /etc/rsyslog.d/04-graylog_mysql.conf
      owner: root
      group: root
      mode: '0644'
    when: mysql_status.rc|int == 0

  - name: Add rsyslog conf for ansible
    copy:
      src: ../files/rsyslog-05-graylog_ansible.conf
      dest: /etc/rsyslog.d/05-graylog_ansible.conf
      owner: root
      group: root
      mode: '0644'
    when: ansible_exists.stat.exists == True

  - name: Add lines to enable bash logging
    blockinfile:
      path: /etc/bash.bashrc
      insertafter: EOF
      state: present
      block: |
        export PROMPT_COMMAND='RETRN_VAL=$?;logger -p local6.debug "$(whoami) [$$]: $(history 1 | sed "s/^[ ]*[0-9]\+[ ]*//" ) [$RETRN_VAL]"'
#"
# fixing yaml with above

  - name: Make sure ZSH installed
    apt:
      name: zsh
      state: present

  - name: Add line to global zshrc for logging
    blockinfile: 
      path: /etc/zsh/zshrc
      insertafter: EOF
      state: present
      block: |
        precmd() { eval 'RETRN_VAL=$?;logger -p local6.debug "$(whoami) [$$]: $(history | tail -n1 | sed "s/^[ ]*[0-9]\+[ ]*//" ) [$RETRN_VAL]"' }
    #when: web15c_zshrc_exists.stat.exists == True
    #with_fileglob:
    #  - "/home/*/.zshrc"

  - name: Add rsyslog conf for bash/zsh_history
    copy:
      src: ../files/rsyslog-06-graylog_bash_zsh.conf
      dest: /etc/rsyslog.d/06-graylog_bash_zsh.conf
      owner: root
      group: root
      mode: '0644'
    # also want this
    # use "facility:local6" in graylog to find all entries
    

  - name: Restart rsyslog service after line appended
    systemd:
      name: rsyslog
      state: restarted
