---
- name: Install python docker packages
  apt:
    pkg:
    - python-docker
    - python3-pip
 
# pip3 install --upgrade pip
# pip3 install docker
#- name: Update pip
#  shell:
#    cmd: pip3 install --upgrade pip
- name: Update pip
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Install pip package
  pip:
    name: docker   
 
- name: Set Docker container parameters
  set_fact:
    node_exporter_container_parameters:
      name: "{{ node_exporter_name }}"
      image: "{{ node_exporter_image }}"
      state: started
      ports:
        - "{{ node_exporter_ports }}"  

- name: Create Node-Exporter container
  docker_container: "{{ node_exporter_container_parameters | combine(node_exporter_docker_additional_options) }}"
  register: node_exporter_container
