---
# If no PHP version installed, playbook doesn't work
# Good for upgrading from 7.X to {{wanted_php_version}}
# because I'm awful and lazy, just install something like "php7.2" then this will handle the rest
- name: Check for php version
  shell: php -v | grep -Po '(?<=PHP )([0-9.][0-9.][0-9])'
  register: php_version

- name: Print php version
  debug:
    msg: "{{ php_version.stdout | float }}"

- name: Print wanted_php_version
  debug:
    msg: "{{ wanted_php_version | float }}"

- name: Check if Apache exists
  shell: systemctl status apache2
  failed_when: false
  changed_when: false
  register: apache_status

- name: Add ondrej apache2 php repo
  apt_repository:
    repo: ppa:ondrej/apache2 
    state: present
  when: apache_status.rc|int == 0 and ansible_distribution == 'Ubuntu' and php_version.stdout|float < wanted_php_version|float and ansible_distribution_version <= '20.04'

- name: Update Apache2 for new repo
  apt:
    name: apache2
    state: present
  when: apache_status.rc|int == 0 and ansible_distribution == 'Ubuntu' and php_version.stdout|float < wanted_php_version|float
  register: apache2

- name: Add PHP repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  when: ansible_distribution == 'Ubuntu' and php_version.stdout|float < wanted_php_version|float and ansible_distribution_version <= '20.04'

- name: Update PHP to {{ wanted_php_version }}
  apt:
    pkg:
    - libapache2-mod-php{{ wanted_php_version }}
    - php{{ wanted_php_version }}
    - php{{ wanted_php_version }}-cli
    - php{{ wanted_php_version }}-curl
    - php{{ wanted_php_version }}-gd
    - php{{ wanted_php_version }}-json
    - php{{ wanted_php_version }}-mbstring
    - php{{ wanted_php_version }}-mysql
    - php{{ wanted_php_version }}-snmp
    - php{{ wanted_php_version }}-xml
    - php{{ wanted_php_version }}-zip
    - php{{ wanted_php_version }}-memcached
    - php{{ wanted_php_version }}-ldap
    - python3-pip
    state: present
    update_cache: yes
    autoremove: yes
    autoclean: yes
  when: ansible_distribution == 'Ubuntu'
  register: php_update

- name: Hold PHP packages to specified version
  dpkg_selections:
    name: "{{ item }}" 
    selection: hold
  loop: 
    - libapache2-mod-php{{ wanted_php_version }}
    - php{{ wanted_php_version }}
    - php{{ wanted_php_version }}-cli
    - php{{ wanted_php_version }}-curl
    - php{{ wanted_php_version }}-gd
    - php{{ wanted_php_version }}-json
    - php{{ wanted_php_version }}-mbstring
    - php{{ wanted_php_version }}-mysql
    - php{{ wanted_php_version }}-snmp
    - php{{ wanted_php_version }}-xml
    - php{{ wanted_php_version }}-zip
    - php{{ wanted_php_version }}-memcached
    - php{{ wanted_php_version }}-ldap
    - python3-pip
  when: ansible_distribution == 'Ubuntu'


- name: Set php timezone
  lineinfile:
    path: /etc/php/{{ wanted_php_version }}/cli/php.ini
    regexp: '^;date.timezone ='
    line: date.timezone = America/New_York
    create: no
 
- name: Set php timezone for apache
  lineinfile:
    path: /etc/php/{{ wanted_php_version }}/apache2/php.ini
    regexp: '^;date.timezone ='
    line: date.timezone = America/New_York
    create: no

- name: Start Apache if it was just installed or php updated
  systemd:
    state: started
    name: apache2
  when: apache2.changed or php_update.changed
